import 'dart:io';
import 'dart:math' as math;

import '../lib/data/poi_catalog_kind.dart';

/// Deduplicates POIs by normalized name + proximity (~80m).
List<PoiCatalogEntry> dedupePoiCatalog(List<PoiCatalogEntry> entries) {
  final kept = <PoiCatalogEntry>[];
  for (final entry in entries) {
    final duplicate = kept.any(
      (other) =>
          other.kind == entry.kind &&
          _normalizedName(other.name) == _normalizedName(entry.name) &&
          _approxMeters(other.lat, other.lon, entry.lat, entry.lon) < 80,
    );
    if (!duplicate) kept.add(entry);
  }
  kept.sort((a, b) {
    final byKind = a.kind.name.compareTo(b.kind.name);
    if (byKind != 0) return byKind;
    return a.name.toLowerCase().compareTo(b.name.toLowerCase());
  });
  return kept;
}

Map<PoiCatalogKind, int> countByKind(List<PoiCatalogEntry> entries) {
  final counts = <PoiCatalogKind, int>{};
  for (final entry in entries) {
    counts[entry.kind] = (counts[entry.kind] ?? 0) + 1;
  }
  return counts;
}

Future<void> writePoiCatalogDart({
  required String outputPath,
  required String regionId,
  required List<PoiCatalogEntry> entries,
  DateTime? generatedAt,
}) async {
  final generated = (generatedAt ?? DateTime.now()).toUtc();
  final iso = generated.toIso8601String();

  final buffer = StringBuffer()
    ..writeln('// GENERATED BY tool/seed_dublin_pois.dart — DO NOT EDIT BY HAND.')
    ..writeln('//')
    ..writeln('// Region: $regionId')
    ..writeln('// Source: OpenStreetMap via Overpass API')
    ..writeln('// POIs: ${entries.length}')
    ..writeln('// Generated: $iso')
    ..writeln('// Re-run quarterly: dart run tool/seed_dublin_pois.dart --full --region=dublin')
    ..writeln('')
    ..writeln("import '../poi_catalog_kind.dart';")
    ..writeln('')
    ..writeln('/// ISO-8601 UTC timestamp when this catalog was last generated.')
    ..writeln("const dublinPoiCatalogGeneratedAt = '$iso';")
    ..writeln('')
    ..writeln('/// Seeded $regionId metro POI catalog (© OpenStreetMap contributors).')
    ..writeln('const List<PoiCatalogEntry> dublinPoiCatalog = [');

  for (final entry in entries) {
    final name = _escapeDartString(entry.name);
    buffer.writeln(
      "  PoiCatalogEntry(name: '$name', lat: ${entry.lat.toStringAsFixed(6)}, lon: ${entry.lon.toStringAsFixed(6)}, kind: PoiCatalogKind.${entry.kind.name}),",
    );
  }

  buffer.writeln('];');
  buffer.writeln('');

  await File(outputPath).writeAsString(buffer.toString());
}

String _escapeDartString(String value) =>
    value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

String _normalizedName(String name) =>
    name.trim().toLowerCase().replaceAll(RegExp(r'\s+'), ' ');

double _approxMeters(double lat1, double lon1, double lat2, double lon2) {
  const metersPerDegLat = 111320.0;
  final metersPerDegLon =
      111320.0 * math.cos(lat1 * math.pi / 180.0);
  final dLat = (lat2 - lat1) * metersPerDegLat;
  final dLon = (lon2 - lon1) * metersPerDegLon;
  return math.sqrt(dLat * dLat + dLon * dLon);
}
